# https://devdiv.visualstudio.com/DevDiv/_build?definitionId=14205&_a=summary

resources:
  repositories:
  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/main
    endpoint: xamarin
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

trigger:
  batch: false
  branches:
    include:
    - main
pr:
  - main

variables:
- template: build/variables.yml
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)\build\tsaoptions-v2.json
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\build\CredScanSuppressions.json
      codeinspector:
        enabled: true
      policheck:
        enabled: true
        exclusionsFile: $(Build.SourcesDirectory)\build\PoliCheckExclusions.xml
      codeSignValidation:
        enabled: true
        break: true
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - template: build/stages/build.yml
    - template: build/stages/test.yml
    - template: build/stages/package.yml
