//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit position must be between 0 and 7.
        /// </summary>
        internal static string ByteExtensions_InvalidBitPosition {
            get {
                return ResourceManager.GetString("ByteExtensions_InvalidBitPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte index must be from 1 to 8, starting from msb.
        /// </summary>
        internal static string ByteExtensions_InvalidByteIndex {
            get {
                return ResourceManager.GetString("ByteExtensions_InvalidByteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bits 7-1 from Acknowledge flags are reserved and must be set to 0.
        /// </summary>
        internal static string ConnectAckFormatter_InvalidAckFlags {
            get {
                return ResourceManager.GetString("ConnectAckFormatter_InvalidAckFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Present flag must be set to 0 for non-zero return codes.
        /// </summary>
        internal static string ConnectAckFormatter_InvalidSessionPresentForErrorReturnCode {
            get {
                return ResourceManager.GetString("ConnectAckFormatter_InvalidSessionPresentForErrorReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id cannot exceed 23 bytes.
        /// </summary>
        internal static string ConnectFormatter_ClientIdMaxLengthExceeded {
            get {
                return ResourceManager.GetString("ConnectFormatter_ClientIdMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id value is cannot be null or empty.
        /// </summary>
        internal static string ConnectFormatter_ClientIdRequired {
            get {
                return ResourceManager.GetString("ConnectFormatter_ClientIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid ClientId. It must contain only numbers and letters.
        /// </summary>
        internal static string ConnectFormatter_InvalidClientIdFormat {
            get {
                return ResourceManager.GetString("ConnectFormatter_InvalidClientIdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Flag must be set to 0 if the User Name Flag is set to 0.
        /// </summary>
        internal static string ConnectFormatter_InvalidPasswordFlag {
            get {
                return ResourceManager.GetString("ConnectFormatter_InvalidPasswordFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid protocol name.
        /// </summary>
        internal static string ConnectFormatter_InvalidProtocolName {
            get {
                return ResourceManager.GetString("ConnectFormatter_InvalidProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved Flag must be always set to 0.
        /// </summary>
        internal static string ConnectFormatter_InvalidReservedFlag {
            get {
                return ResourceManager.GetString("ConnectFormatter_InvalidReservedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Retain Flag must be set to 0 if the Will Flag is set to 0.
        /// </summary>
        internal static string ConnectFormatter_InvalidWillRetainFlag {
            get {
                return ResourceManager.GetString("ConnectFormatter_InvalidWillRetainFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password value must be null or empty if User value is null or empty.
        /// </summary>
        internal static string ConnectFormatter_PasswordNotAllowed {
            get {
                return ResourceManager.GetString("ConnectFormatter_PasswordNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value cannot exceed 65536 bytes of length.
        /// </summary>
        internal static string DataRepresentationExtensions_StringMaxLengthExceeded {
            get {
                return ResourceManager.GetString("DataRepresentationExtensions_StringMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Flag {0} is invalid for {1} message. Expected value: {2}.
        /// </summary>
        internal static string Formatter_InvalidHeaderFlag {
            get {
                return ResourceManager.GetString("Formatter_InvalidHeaderFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message sent cannot be handled by {0}.
        /// </summary>
        internal static string Formatter_InvalidMessage {
            get {
                return ResourceManager.GetString("Formatter_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet sent cannot be handled by {0}.
        /// </summary>
        internal static string Formatter_InvalidPacket {
            get {
                return ResourceManager.GetString("Formatter_InvalidPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qos value must be from 0x00 to 0x02.
        /// </summary>
        internal static string Formatter_InvalidQualityOfService {
            get {
                return ResourceManager.GetString("Formatter_InvalidQualityOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message is not valid.
        /// </summary>
        internal static string Formatter_MessageTypeNotAllowed {
            get {
                return ResourceManager.GetString("Formatter_MessageTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message received cannot be handled by any of the registered formatters.
        /// </summary>
        internal static string MessageManager_MessageUnknown {
            get {
                return ResourceManager.GetString("MessageManager_MessageUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received packet cannot be handled by any of the registered formatters.
        /// </summary>
        internal static string MessageManager_PacketUnknown {
            get {
                return ResourceManager.GetString("MessageManager_PacketUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed Remaining Length.
        /// </summary>
        internal static string ProtocolEncoding_MalformedRemainingLength {
            get {
                return ResourceManager.GetString("ProtocolEncoding_MalformedRemainingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated flag must be set to 0 if the QoS is 0.
        /// </summary>
        internal static string PublishFormatter_InvalidDuplicatedWithQoSZero {
            get {
                return ResourceManager.GetString("PublishFormatter_InvalidDuplicatedWithQoSZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id is not allowed for packets with QoS 0.
        /// </summary>
        internal static string PublishFormatter_InvalidMessageId {
            get {
                return ResourceManager.GetString("PublishFormatter_InvalidMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name {0} is invalid. It cannot be null or empty and It must not contain wildcard characters .
        /// </summary>
        internal static string PublishFormatter_InvalidTopicName {
            get {
                return ResourceManager.GetString("PublishFormatter_InvalidTopicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Id value is cannot be null or empty for packets with QoS 1 or 2.
        /// </summary>
        internal static string PublishFormatter_MessageIdRequired {
            get {
                return ResourceManager.GetString("PublishFormatter_MessageIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return codes can only be valid QoS values or a failure code (0x80).
        /// </summary>
        internal static string SubscribeAckFormatter_InvalidReturnCodes {
            get {
                return ResourceManager.GetString("SubscribeAckFormatter_InvalidReturnCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscribe acknowledge packet must contain at least one return code.
        /// </summary>
        internal static string SubscribeAckFormatter_MissingReturnCodes {
            get {
                return ResourceManager.GetString("SubscribeAckFormatter_MissingReturnCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subscribe packet must contain at least one Topic Filter / QoS pair.
        /// </summary>
        internal static string SubscribeFormatter_MissingTopicFilterQosPair {
            get {
                return ResourceManager.GetString("SubscribeFormatter_MissingTopicFilterQosPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsubscribe packet must contain at least one topic to unsubscribe.
        /// </summary>
        internal static string UnsubscribeFormatter_MissingTopics {
            get {
                return ResourceManager.GetString("UnsubscribeFormatter_MissingTopics", resourceCulture);
            }
        }
    }
}
