//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client {0} has been disconnected while trying to perform the connection.
        /// </summary>
        internal static string Client_ConnectionDisconnected {
            get {
                return ResourceManager.GetString("Client_ConnectionDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to connect the client {0}.
        /// </summary>
        internal static string Client_ConnectionError {
            get {
                return ResourceManager.GetString("Client_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occured while waiting for the client {0} connection confirmation.
        /// </summary>
        internal static string Client_ConnectionTimeout {
            get {
                return ResourceManager.GetString("Client_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to subscribe the client {0} to topic {1}.
        /// </summary>
        internal static string Client_SubscribeError {
            get {
                return ResourceManager.GetString("Client_SubscribeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occured while waiting for the subscribe confirmation of client {0} for topic {1}.
        /// </summary>
        internal static string Client_SubscribeTimeout {
            get {
                return ResourceManager.GetString("Client_SubscribeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client {0} has been disconnected while trying to perform the subscription to topic {1}.
        /// </summary>
        internal static string Client_SubscriptionDisconnected {
            get {
                return ResourceManager.GetString("Client_SubscriptionDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying connection has been disconnected unexpectedly.
        /// </summary>
        internal static string Client_UnexpectedChannelDisconnection {
            get {
                return ResourceManager.GetString("Client_UnexpectedChannelDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first packet received from the Server must be a ConnectAck packet. The connection will be closed..
        /// </summary>
        internal static string ClientPacketChannelAdapter_FirstReceivedPacketMustBeConnectAck {
            get {
                return ResourceManager.GetString("ClientPacketChannelAdapter_FirstReceivedPacketMustBeConnectAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ConnectAck has been received since the connection was established. The connection will be closed..
        /// </summary>
        internal static string ClientPacketChannelAdapter_NoConnectAckReceived {
            get {
                return ResourceManager.GetString("ClientPacketChannelAdapter_NoConnectAckReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying TCP client is not connected.
        /// </summary>
        internal static string TcpChannel_ClientIsNotConnected {
            get {
                return ResourceManager.GetString("TcpChannel_ClientIsNotConnected", resourceCulture);
            }
        }
    }
}
